insert into status_disp (status_id, clave, descripcion) values (1, 'AV', 'integer non velit donec diam neque vestibulum eget vulputate ut ultrices vel augue vestibulum ante ipsum');
insert into status_disp (status_id, clave, descripcion) values (2, 'FU', 'auctor gravida sem praesent id massa id nisl venenatis lacinia aenean sit amet justo morbi ut');
insert into status_disp (status_id, clave, descripcion) values (3, 'REP', 'id nulla ultrices aliquet maecenas leo odio condimentum id luctus');
insert into status_disp (status_id, clave, descripcion) values (4, 'AV', 'ante nulla justo aliquam quis turpis eget elit sodales scelerisque mauris sit amet eros');
insert into status_disp (status_id, clave, descripcion) values (5, 'AV', 'at feugiat non pretium quis lectus suspendisse potenti in eleifend quam');
insert into status_disp (status_id, clave, descripcion) values (6, 'VIG', 'donec quis orci eget orci vehicula condimentum curabitur in libero ut massa');
insert into status_disp (status_id, clave, descripcion) values (7, 'VIG', 'curabitur convallis duis consequat dui nec nisi volutpat eleifend donec ut dolor morbi vel lectus in quam fringilla');
insert into status_disp (status_id, clave, descripcion) values (8, 'FU', 'vitae nisi nam ultrices libero non mattis pulvinar nulla pede ullamcorper augue a suscipit nulla elit ac nulla');
insert into status_disp (status_id, clave, descripcion) values (9, 'OBS', 'ante nulla justo aliquam quis turpis eget elit sodales scelerisque mauris sit amet eros suspendisse accumsan tortor quis turpis sed');
insert into status_disp (status_id, clave, descripcion) values (10, 'VIG', 'erat id mauris vulputate elementum nullam varius nulla facilisi cras non velit nec');
insert into status_disp (status_id, clave, descripcion) values (11, 'REP', 'nibh in quis justo maecenas rhoncus aliquam lacus morbi quis tortor id nulla ultrices aliquet maecenas');
insert into status_disp (status_id, clave, descripcion) values (12, 'AV', 'amet sem fusce consequat nulla nisl nunc nisl duis bibendum felis sed interdum venenatis turpis enim');
insert into status_disp (status_id, clave, descripcion) values (13, 'AV', 'quam pharetra magna ac consequat metus sapien ut nunc vestibulum ante ipsum primis in faucibus');
insert into status_disp (status_id, clave, descripcion) values (14, 'OBS', 'non velit donec diam neque vestibulum eget vulputate ut ultrices vel augue vestibulum ante ipsum');
insert into status_disp (status_id, clave, descripcion) values (15, 'AV', 'eros elementum pellentesque quisque porta volutpat erat quisque erat eros viverra eget congue eget semper rutrum');
insert into status_disp (status_id, clave, descripcion) values (16, 'REP', 'ut massa quis augue luctus tincidunt nulla mollis molestie lorem quisque ut erat curabitur gravida nisi');
insert into status_disp (status_id, clave, descripcion) values (17, 'AV', 'augue luctus tincidunt nulla mollis molestie lorem quisque ut erat curabitur gravida nisi at');
insert into status_disp (status_id, clave, descripcion) values (18, 'VIG', 'lacus curabitur at ipsum ac tellus semper interdum mauris ullamcorper purus');
insert into status_disp (status_id, clave, descripcion) values (19, 'FU', 'vestibulum sagittis sapien cum sociis natoque penatibus et magnis dis parturient montes nascetur');
insert into status_disp (status_id, clave, descripcion) values (20, 'AV', 'nec dui luctus rutrum nulla tellus in sagittis dui vel nisl duis ac nibh fusce lacus purus aliquet at');
insert into status_disp (status_id, clave, descripcion) values (21, 'FU', 'vel ipsum praesent blandit lacinia erat vestibulum sed magna at nunc commodo');
insert into status_disp (status_id, clave, descripcion) values (22, 'AV', 'congue diam id ornare imperdiet sapien urna pretium nisl ut volutpat sapien arcu sed augue aliquam erat');
insert into status_disp (status_id, clave, descripcion) values (23, 'FU', 'convallis morbi odio odio elementum eu interdum eu tincidunt in leo maecenas');
insert into status_disp (status_id, clave, descripcion) values (24, 'OBS', 'erat fermentum justo nec condimentum neque sapien placerat ante nulla justo aliquam quis turpis eget elit sodales');
insert into status_disp (status_id, clave, descripcion) values (25, 'FU', 'dolor sit amet consectetuer adipiscing elit proin risus praesent lectus vestibulum');
insert into status_disp (status_id, clave, descripcion) values (26, 'VIG', 'parturient montes nascetur ridiculus mus vivamus vestibulum sagittis sapien cum sociis natoque penatibus');
insert into status_disp (status_id, clave, descripcion) values (27, 'REP', 'cursus vestibulum proin eu mi nulla ac enim in tempor turpis nec euismod scelerisque quam turpis adipiscing lorem vitae mattis');
insert into status_disp (status_id, clave, descripcion) values (28, 'AV', 'etiam faucibus cursus urna ut tellus nulla ut erat id mauris vulputate elementum nullam varius nulla');
insert into status_disp (status_id, clave, descripcion) values (29, 'OBS', 'quisque erat eros viverra eget congue eget semper rutrum nulla nunc purus phasellus in felis donec semper');
insert into status_disp (status_id, clave, descripcion) values (30, 'REP', 'porta volutpat quam pede lobortis ligula sit amet eleifend pede libero quis orci nullam molestie');
insert into status_disp (status_id, clave, descripcion) values (31, 'FU', 'dui luctus rutrum nulla tellus in sagittis dui vel nisl duis ac nibh fusce lacus purus');
insert into status_disp (status_id, clave, descripcion) values (32, 'OBS', 'amet consectetuer adipiscing elit proin risus praesent lectus vestibulum quam sapien varius ut blandit non interdum in ante');
insert into status_disp (status_id, clave, descripcion) values (33, 'OBS', 'lectus pellentesque eget nunc donec quis orci eget orci vehicula condimentum curabitur in');
insert into status_disp (status_id, clave, descripcion) values (34, 'REP', 'commodo vulputate justo in blandit ultrices enim lorem ipsum dolor sit amet consectetuer');
insert into status_disp (status_id, clave, descripcion) values (35, 'OBS', 'lacus purus aliquet at feugiat non pretium quis lectus suspendisse');
insert into status_disp (status_id, clave, descripcion) values (36, 'REP', 'erat curabitur gravida nisi at nibh in hac habitasse platea dictumst');
insert into status_disp (status_id, clave, descripcion) values (37, 'AV', 'nunc nisl duis bibendum felis sed interdum venenatis turpis enim blandit');
insert into status_disp (status_id, clave, descripcion) values (38, 'REP', 'ut erat id mauris vulputate elementum nullam varius nulla facilisi cras non velit nec nisi vulputate nonummy');
insert into status_disp (status_id, clave, descripcion) values (39, 'OBS', 'ligula pellentesque ultrices phasellus id sapien in sapien iaculis congue vivamus metus arcu adipiscing molestie hendrerit at');
insert into status_disp (status_id, clave, descripcion) values (40, 'OBS', 'nulla sed vel enim sit amet nunc viverra dapibus nulla suscipit');
insert into status_disp (status_id, clave, descripcion) values (41, 'OBS', 'nulla sed accumsan felis ut at dolor quis odio consequat varius integer ac');
insert into status_disp (status_id, clave, descripcion) values (42, 'OBS', 'faucibus accumsan odio curabitur convallis duis consequat dui nec nisi');
insert into status_disp (status_id, clave, descripcion) values (43, 'VIG', 'est quam pharetra magna ac consequat metus sapien ut nunc vestibulum ante ipsum primis in');
insert into status_disp (status_id, clave, descripcion) values (44, 'OBS', 'nibh in lectus pellentesque at nulla suspendisse potenti cras in purus eu magna vulputate luctus cum sociis natoque penatibus');
insert into status_disp (status_id, clave, descripcion) values (45, 'AV', 'velit donec diam neque vestibulum eget vulputate ut ultrices vel augue vestibulum ante ipsum');
insert into status_disp (status_id, clave, descripcion) values (46, 'VIG', 'curabitur at ipsum ac tellus semper interdum mauris ullamcorper purus sit amet nulla quisque arcu libero');
insert into status_disp (status_id, clave, descripcion) values (47, 'OBS', 'quisque arcu libero rutrum ac lobortis vel dapibus at diam nam tristique tortor eu');
insert into status_disp (status_id, clave, descripcion) values (48, 'VIG', 'odio porttitor id consequat in consequat ut nulla sed accumsan felis ut at dolor quis odio');
insert into status_disp (status_id, clave, descripcion) values (49, 'OBS', 'pulvinar lobortis est phasellus sit amet erat nulla tempus vivamus in felis eu sapien cursus vestibulum proin eu mi');
insert into status_disp (status_id, clave, descripcion) values (50, 'REP', 'turpis enim blandit mi in porttitor pede justo eu massa donec dapibus duis at velit eu est congue');
insert into status_disp (status_id, clave, descripcion) values (51, 'FU', 'cursus id turpis integer aliquet massa id lobortis convallis tortor risus dapibus');
insert into status_disp (status_id, clave, descripcion) values (52, 'AV', 'ac diam cras pellentesque volutpat dui maecenas tristique est et');
insert into status_disp (status_id, clave, descripcion) values (53, 'OBS', 'justo in blandit ultrices enim lorem ipsum dolor sit amet consectetuer adipiscing elit proin interdum mauris non ligula');
insert into status_disp (status_id, clave, descripcion) values (54, 'FU', 'augue vel accumsan tellus nisi eu orci mauris lacinia sapien quis libero nullam sit amet turpis elementum ligula vehicula consequat');
insert into status_disp (status_id, clave, descripcion) values (55, 'OBS', 'potenti in eleifend quam a odio in hac habitasse platea dictumst maecenas ut massa quis augue luctus tincidunt nulla mollis');
insert into status_disp (status_id, clave, descripcion) values (56, 'FU', 'congue elementum in hac habitasse platea dictumst morbi vestibulum velit id pretium iaculis diam erat');
insert into status_disp (status_id, clave, descripcion) values (57, 'AV', 'a suscipit nulla elit ac nulla sed vel enim sit amet nunc viverra dapibus nulla');
insert into status_disp (status_id, clave, descripcion) values (58, 'OBS', 'ut at dolor quis odio consequat varius integer ac leo pellentesque ultrices mattis odio donec vitae nisi nam ultrices libero');
insert into status_disp (status_id, clave, descripcion) values (59, 'VIG', 'natoque penatibus et magnis dis parturient montes nascetur ridiculus mus vivamus vestibulum sagittis sapien cum sociis');
insert into status_disp (status_id, clave, descripcion) values (60, 'OBS', 'lacinia eget tincidunt eget tempus vel pede morbi porttitor lorem id');
insert into status_disp (status_id, clave, descripcion) values (61, 'OBS', 'nec sem duis aliquam convallis nunc proin at turpis a pede posuere nonummy integer non velit');
insert into status_disp (status_id, clave, descripcion) values (62, 'OBS', 'phasellus id sapien in sapien iaculis congue vivamus metus arcu adipiscing molestie hendrerit at vulputate');
insert into status_disp (status_id, clave, descripcion) values (63, 'REP', 'consectetuer eget rutrum at lorem integer tincidunt ante vel ipsum praesent blandit lacinia');
insert into status_disp (status_id, clave, descripcion) values (64, 'VIG', 'sit amet nulla quisque arcu libero rutrum ac lobortis vel dapibus at diam nam tristique tortor');
insert into status_disp (status_id, clave, descripcion) values (65, 'OBS', 'leo rhoncus sed vestibulum sit amet cursus id turpis integer aliquet massa id lobortis convallis tortor risus dapibus');
insert into status_disp (status_id, clave, descripcion) values (66, 'AV', 'arcu sed augue aliquam erat volutpat in congue etiam justo etiam pretium');
insert into status_disp (status_id, clave, descripcion) values (67, 'OBS', 'orci nullam molestie nibh in lectus pellentesque at nulla suspendisse potenti cras in');
insert into status_disp (status_id, clave, descripcion) values (68, 'VIG', 'montes nascetur ridiculus mus vivamus vestibulum sagittis sapien cum sociis natoque');
insert into status_disp (status_id, clave, descripcion) values (69, 'VIG', 'sit amet nunc viverra dapibus nulla suscipit ligula in lacus');
insert into status_disp (status_id, clave, descripcion) values (70, 'REP', 'dapibus nulla suscipit ligula in lacus curabitur at ipsum ac tellus semper interdum mauris ullamcorper');
insert into status_disp (status_id, clave, descripcion) values (71, 'FU', 'semper sapien a libero nam dui proin leo odio porttitor id consequat in consequat ut nulla sed accumsan');
insert into status_disp (status_id, clave, descripcion) values (72, 'FU', 'sodales sed tincidunt eu felis fusce posuere felis sed lacus');
insert into status_disp (status_id, clave, descripcion) values (73, 'OBS', 'non mattis pulvinar nulla pede ullamcorper augue a suscipit nulla elit ac nulla sed vel enim sit');
insert into status_disp (status_id, clave, descripcion) values (74, 'FU', 'quis turpis eget elit sodales scelerisque mauris sit amet eros');
insert into status_disp (status_id, clave, descripcion) values (75, 'FU', 'vestibulum sed magna at nunc commodo placerat praesent blandit nam nulla integer');
insert into status_disp (status_id, clave, descripcion) values (76, 'FU', 'dis parturient montes nascetur ridiculus mus etiam vel augue vestibulum rutrum rutrum neque aenean auctor gravida sem praesent id massa');
insert into status_disp (status_id, clave, descripcion) values (77, 'REP', 'scelerisque quam turpis adipiscing lorem vitae mattis nibh ligula nec sem duis aliquam');
insert into status_disp (status_id, clave, descripcion) values (78, 'AV', 'proin eu mi nulla ac enim in tempor turpis nec euismod scelerisque');
insert into status_disp (status_id, clave, descripcion) values (79, 'FU', 'ornare imperdiet sapien urna pretium nisl ut volutpat sapien arcu sed augue aliquam erat volutpat in congue etiam justo');
insert into status_disp (status_id, clave, descripcion) values (80, 'AV', 'consectetuer adipiscing elit proin risus praesent lectus vestibulum quam sapien varius');
insert into status_disp (status_id, clave, descripcion) values (81, 'OBS', 'mattis pulvinar nulla pede ullamcorper augue a suscipit nulla elit ac nulla sed vel enim sit amet nunc viverra dapibus');
insert into status_disp (status_id, clave, descripcion) values (82, 'AV', 'integer ac neque duis bibendum morbi non quam nec dui luctus rutrum nulla');
insert into status_disp (status_id, clave, descripcion) values (83, 'REP', 'porttitor pede justo eu massa donec dapibus duis at velit eu est congue elementum in hac habitasse platea dictumst');
insert into status_disp (status_id, clave, descripcion) values (84, 'VIG', 'hendrerit at vulputate vitae nisl aenean lectus pellentesque eget nunc donec quis orci eget');
insert into status_disp (status_id, clave, descripcion) values (85, 'REP', 'convallis tortor risus dapibus augue vel accumsan tellus nisi eu');
insert into status_disp (status_id, clave, descripcion) values (86, 'FU', 'at nibh in hac habitasse platea dictumst aliquam augue quam');
insert into status_disp (status_id, clave, descripcion) values (87, 'REP', 'risus semper porta volutpat quam pede lobortis ligula sit amet eleifend pede');
insert into status_disp (status_id, clave, descripcion) values (88, 'VIG', 'ultricies eu nibh quisque id justo sit amet sapien dignissim vestibulum vestibulum ante ipsum');
insert into status_disp (status_id, clave, descripcion) values (89, 'VIG', 'dis parturient montes nascetur ridiculus mus etiam vel augue vestibulum rutrum rutrum');
insert into status_disp (status_id, clave, descripcion) values (90, 'FU', 'nec condimentum neque sapien placerat ante nulla justo aliquam quis turpis eget');
insert into status_disp (status_id, clave, descripcion) values (91, 'FU', 'in eleifend quam a odio in hac habitasse platea dictumst maecenas ut');
insert into status_disp (status_id, clave, descripcion) values (92, 'REP', 'ac nibh fusce lacus purus aliquet at feugiat non pretium');
insert into status_disp (status_id, clave, descripcion) values (93, 'VIG', 'suspendisse accumsan tortor quis turpis sed ante vivamus tortor duis mattis egestas metus aenean fermentum donec ut');
insert into status_disp (status_id, clave, descripcion) values (94, 'AV', 'pede ac diam cras pellentesque volutpat dui maecenas tristique est et tempus semper est quam');
insert into status_disp (status_id, clave, descripcion) values (95, 'OBS', 'justo lacinia eget tincidunt eget tempus vel pede morbi porttitor lorem id ligula suspendisse ornare consequat lectus in');
insert into status_disp (status_id, clave, descripcion) values (96, 'REP', 'parturient montes nascetur ridiculus mus vivamus vestibulum sagittis sapien cum sociis natoque penatibus et magnis dis parturient montes nascetur ridiculus');
insert into status_disp (status_id, clave, descripcion) values (97, 'VIG', 'a pede posuere nonummy integer non velit donec diam neque vestibulum eget vulputate ut ultrices vel augue');
insert into status_disp (status_id, clave, descripcion) values (98, 'OBS', 'platea dictumst maecenas ut massa quis augue luctus tincidunt nulla mollis molestie lorem quisque ut erat curabitur gravida nisi at');
insert into status_disp (status_id, clave, descripcion) values (99, 'OBS', 'venenatis non sodales sed tincidunt eu felis fusce posuere felis sed lacus');
insert into status_disp (status_id, clave, descripcion) values (100, 'VIG', 'ante nulla justo aliquam quis turpis eget elit sodales scelerisque mauris sit amet eros suspendisse accumsan tortor');
insert into status_disp (status_id, clave, descripcion) values (101, 'FU', 'vestibulum rutrum rutrum neque aenean auctor gravida sem praesent id massa id nisl venenatis lacinia aenean sit amet justo');
insert into status_disp (status_id, clave, descripcion) values (102, 'REP', 'vivamus metus arcu adipiscing molestie hendrerit at vulputate vitae nisl aenean lectus pellentesque');
insert into status_disp (status_id, clave, descripcion) values (103, 'VIG', 'lorem ipsum dolor sit amet consectetuer adipiscing elit proin risus praesent lectus vestibulum quam sapien varius ut blandit non');
insert into status_disp (status_id, clave, descripcion) values (104, 'OBS', 'in eleifend quam a odio in hac habitasse platea dictumst maecenas ut massa quis');
insert into status_disp (status_id, clave, descripcion) values (105, 'AV', 'ut dolor morbi vel lectus in quam fringilla rhoncus mauris enim leo');
insert into status_disp (status_id, clave, descripcion) values (106, 'OBS', 'natoque penatibus et magnis dis parturient montes nascetur ridiculus mus etiam vel augue vestibulum rutrum rutrum');
insert into status_disp (status_id, clave, descripcion) values (107, 'AV', 'consectetuer adipiscing elit proin interdum mauris non ligula pellentesque ultrices phasellus id');
insert into status_disp (status_id, clave, descripcion) values (108, 'VIG', 'feugiat non pretium quis lectus suspendisse potenti in eleifend quam a odio in hac habitasse platea dictumst maecenas ut massa');
insert into status_disp (status_id, clave, descripcion) values (109, 'FU', 'potenti cras in purus eu magna vulputate luctus cum sociis natoque penatibus et');
insert into status_disp (status_id, clave, descripcion) values (110, 'VIG', 'dictumst maecenas ut massa quis augue luctus tincidunt nulla mollis molestie lorem quisque ut');
insert into status_disp (status_id, clave, descripcion) values (111, 'REP', 'consequat morbi a ipsum integer a nibh in quis justo maecenas rhoncus aliquam lacus morbi quis tortor id nulla');
insert into status_disp (status_id, clave, descripcion) values (112, 'AV', 'lacus curabitur at ipsum ac tellus semper interdum mauris ullamcorper purus sit amet nulla quisque');
insert into status_disp (status_id, clave, descripcion) values (113, 'FU', 'turpis integer aliquet massa id lobortis convallis tortor risus dapibus augue vel accumsan tellus nisi');
insert into status_disp (status_id, clave, descripcion) values (114, 'REP', 'iaculis diam erat fermentum justo nec condimentum neque sapien placerat ante nulla justo aliquam quis turpis eget elit');
insert into status_disp (status_id, clave, descripcion) values (115, 'VIG', 'ut massa volutpat convallis morbi odio odio elementum eu interdum eu tincidunt in leo maecenas');
insert into status_disp (status_id, clave, descripcion) values (116, 'REP', 'nonummy integer non velit donec diam neque vestibulum eget vulputate ut');
insert into status_disp (status_id, clave, descripcion) values (117, 'AV', 'in hac habitasse platea dictumst etiam faucibus cursus urna ut tellus nulla ut erat');
insert into status_disp (status_id, clave, descripcion) values (118, 'OBS', 'eu tincidunt in leo maecenas pulvinar lobortis est phasellus sit amet erat nulla tempus vivamus');
insert into status_disp (status_id, clave, descripcion) values (119, 'VIG', 'accumsan felis ut at dolor quis odio consequat varius integer');
insert into status_disp (status_id, clave, descripcion) values (120, 'VIG', 'non pretium quis lectus suspendisse potenti in eleifend quam a odio in hac habitasse platea dictumst maecenas ut');
insert into status_disp (status_id, clave, descripcion) values (121, 'REP', 'interdum venenatis turpis enim blandit mi in porttitor pede justo eu');
insert into status_disp (status_id, clave, descripcion) values (122, 'VIG', 'ullamcorper purus sit amet nulla quisque arcu libero rutrum ac lobortis');
insert into status_disp (status_id, clave, descripcion) values (123, 'VIG', 'ipsum integer a nibh in quis justo maecenas rhoncus aliquam lacus morbi');
insert into status_disp (status_id, clave, descripcion) values (124, 'VIG', 'penatibus et magnis dis parturient montes nascetur ridiculus mus etiam vel augue vestibulum rutrum rutrum neque aenean auctor gravida');
insert into status_disp (status_id, clave, descripcion) values (125, 'REP', 'sed nisl nunc rhoncus dui vel sem sed sagittis nam congue risus semper porta volutpat');
insert into status_disp (status_id, clave, descripcion) values (126, 'VIG', 'in faucibus orci luctus et ultrices posuere cubilia curae nulla dapibus dolor vel est donec odio');
insert into status_disp (status_id, clave, descripcion) values (127, 'FU', 'quis justo maecenas rhoncus aliquam lacus morbi quis tortor id nulla ultrices aliquet');
insert into status_disp (status_id, clave, descripcion) values (128, 'OBS', 'id pretium iaculis diam erat fermentum justo nec condimentum neque sapien placerat ante nulla justo');
insert into status_disp (status_id, clave, descripcion) values (129, 'AV', 'id lobortis convallis tortor risus dapibus augue vel accumsan tellus');
insert into status_disp (status_id, clave, descripcion) values (130, 'VIG', 'nisl nunc rhoncus dui vel sem sed sagittis nam congue risus semper porta volutpat quam pede lobortis');
insert into status_disp (status_id, clave, descripcion) values (131, 'FU', 'et ultrices posuere cubilia curae duis faucibus accumsan odio curabitur convallis duis consequat');
insert into status_disp (status_id, clave, descripcion) values (132, 'VIG', 'ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae duis faucibus accumsan odio curabitur');
insert into status_disp (status_id, clave, descripcion) values (133, 'REP', 'sit amet sem fusce consequat nulla nisl nunc nisl duis bibendum');
insert into status_disp (status_id, clave, descripcion) values (134, 'AV', 'massa id nisl venenatis lacinia aenean sit amet justo morbi ut odio cras');
insert into status_disp (status_id, clave, descripcion) values (135, 'OBS', 'at vulputate vitae nisl aenean lectus pellentesque eget nunc donec');
insert into status_disp (status_id, clave, descripcion) values (136, 'REP', 'nisl ut volutpat sapien arcu sed augue aliquam erat volutpat');
insert into status_disp (status_id, clave, descripcion) values (137, 'AV', 'integer non velit donec diam neque vestibulum eget vulputate ut ultrices vel augue vestibulum');
insert into status_disp (status_id, clave, descripcion) values (138, 'VIG', 'duis bibendum felis sed interdum venenatis turpis enim blandit mi in porttitor pede justo eu');
insert into status_disp (status_id, clave, descripcion) values (139, 'OBS', 'sem praesent id massa id nisl venenatis lacinia aenean sit amet');
insert into status_disp (status_id, clave, descripcion) values (140, 'FU', 'vel sem sed sagittis nam congue risus semper porta volutpat quam pede lobortis ligula sit amet');
insert into status_disp (status_id, clave, descripcion) values (141, 'REP', 'duis faucibus accumsan odio curabitur convallis duis consequat dui nec nisi');
insert into status_disp (status_id, clave, descripcion) values (142, 'AV', 'nulla elit ac nulla sed vel enim sit amet nunc viverra dapibus nulla suscipit ligula in lacus curabitur at ipsum');
insert into status_disp (status_id, clave, descripcion) values (143, 'VIG', 'eleifend pede libero quis orci nullam molestie nibh in lectus pellentesque at nulla suspendisse potenti');
insert into status_disp (status_id, clave, descripcion) values (144, 'FU', 'aenean auctor gravida sem praesent id massa id nisl venenatis lacinia aenean sit amet justo');
insert into status_disp (status_id, clave, descripcion) values (145, 'VIG', 'viverra dapibus nulla suscipit ligula in lacus curabitur at ipsum ac tellus semper interdum mauris ullamcorper purus sit amet nulla');
insert into status_disp (status_id, clave, descripcion) values (146, 'OBS', 'erat vestibulum sed magna at nunc commodo placerat praesent blandit nam nulla');
insert into status_disp (status_id, clave, descripcion) values (147, 'FU', 'quis tortor id nulla ultrices aliquet maecenas leo odio condimentum id luctus nec molestie sed justo pellentesque');
insert into status_disp (status_id, clave, descripcion) values (148, 'OBS', 'bibendum imperdiet nullam orci pede venenatis non sodales sed tincidunt eu felis fusce posuere felis sed lacus morbi sem');
insert into status_disp (status_id, clave, descripcion) values (149, 'OBS', 'ante nulla justo aliquam quis turpis eget elit sodales scelerisque mauris sit amet eros suspendisse accumsan');
insert into status_disp (status_id, clave, descripcion) values (150, 'AV', 'vivamus vel nulla eget eros elementum pellentesque quisque porta volutpat erat quisque erat eros viverra eget congue eget');
insert into status_disp (status_id, clave, descripcion) values (151, 'AV', 'quis turpis sed ante vivamus tortor duis mattis egestas metus aenean fermentum donec ut mauris eget massa tempor convallis');
insert into status_disp (status_id, clave, descripcion) values (152, 'REP', 'quis turpis eget elit sodales scelerisque mauris sit amet eros suspendisse accumsan');
insert into status_disp (status_id, clave, descripcion) values (153, 'FU', 'elementum ligula vehicula consequat morbi a ipsum integer a nibh in quis justo maecenas rhoncus aliquam lacus');
insert into status_disp (status_id, clave, descripcion) values (154, 'AV', 'amet nulla quisque arcu libero rutrum ac lobortis vel dapibus at diam nam tristique tortor');
insert into status_disp (status_id, clave, descripcion) values (155, 'REP', 'ultrices posuere cubilia curae donec pharetra magna vestibulum aliquet ultrices erat');
insert into status_disp (status_id, clave, descripcion) values (156, 'FU', 'nunc commodo placerat praesent blandit nam nulla integer pede justo lacinia eget tincidunt eget');
insert into status_disp (status_id, clave, descripcion) values (157, 'FU', 'risus semper porta volutpat quam pede lobortis ligula sit amet eleifend pede libero quis orci nullam');
insert into status_disp (status_id, clave, descripcion) values (158, 'REP', 'diam neque vestibulum eget vulputate ut ultrices vel augue vestibulum ante');
insert into status_disp (status_id, clave, descripcion) values (159, 'REP', 'sapien quis libero nullam sit amet turpis elementum ligula vehicula consequat morbi a');
insert into status_disp (status_id, clave, descripcion) values (160, 'VIG', 'et ultrices posuere cubilia curae donec pharetra magna vestibulum aliquet ultrices erat tortor sollicitudin mi sit amet lobortis sapien');
insert into status_disp (status_id, clave, descripcion) values (161, 'VIG', 'vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere');
insert into status_disp (status_id, clave, descripcion) values (162, 'REP', 'integer tincidunt ante vel ipsum praesent blandit lacinia erat vestibulum sed magna');
insert into status_disp (status_id, clave, descripcion) values (163, 'REP', 'mauris non ligula pellentesque ultrices phasellus id sapien in sapien iaculis congue vivamus metus arcu adipiscing molestie hendrerit');
insert into status_disp (status_id, clave, descripcion) values (164, 'AV', 'amet turpis elementum ligula vehicula consequat morbi a ipsum integer a nibh in quis justo maecenas rhoncus');
insert into status_disp (status_id, clave, descripcion) values (165, 'REP', 'ac leo pellentesque ultrices mattis odio donec vitae nisi nam');
insert into status_disp (status_id, clave, descripcion) values (166, 'REP', 'vestibulum sed magna at nunc commodo placerat praesent blandit nam nulla integer pede justo lacinia eget tincidunt eget tempus');
insert into status_disp (status_id, clave, descripcion) values (167, 'FU', 'dapibus nulla suscipit ligula in lacus curabitur at ipsum ac tellus');
insert into status_disp (status_id, clave, descripcion) values (168, 'REP', 'sem mauris laoreet ut rhoncus aliquet pulvinar sed nisl nunc rhoncus dui');
insert into status_disp (status_id, clave, descripcion) values (169, 'VIG', 'semper rutrum nulla nunc purus phasellus in felis donec semper sapien a');
insert into status_disp (status_id, clave, descripcion) values (170, 'VIG', 'vulputate ut ultrices vel augue vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae donec pharetra');
insert into status_disp (status_id, clave, descripcion) values (171, 'FU', 'adipiscing elit proin risus praesent lectus vestibulum quam sapien varius');
insert into status_disp (status_id, clave, descripcion) values (172, 'VIG', 'malesuada in imperdiet et commodo vulputate justo in blandit ultrices');
insert into status_disp (status_id, clave, descripcion) values (173, 'VIG', 'interdum eu tincidunt in leo maecenas pulvinar lobortis est phasellus sit amet erat nulla tempus vivamus in felis eu sapien');
insert into status_disp (status_id, clave, descripcion) values (174, 'VIG', 'volutpat erat quisque erat eros viverra eget congue eget semper rutrum');
insert into status_disp (status_id, clave, descripcion) values (175, 'FU', 'quam nec dui luctus rutrum nulla tellus in sagittis dui vel');
insert into status_disp (status_id, clave, descripcion) values (176, 'REP', 'nullam porttitor lacus at turpis donec posuere metus vitae ipsum aliquam non');
insert into status_disp (status_id, clave, descripcion) values (177, 'FU', 'vel pede morbi porttitor lorem id ligula suspendisse ornare consequat lectus in est risus auctor');
insert into status_disp (status_id, clave, descripcion) values (178, 'OBS', 'lobortis vel dapibus at diam nam tristique tortor eu pede');
insert into status_disp (status_id, clave, descripcion) values (179, 'REP', 'orci vehicula condimentum curabitur in libero ut massa volutpat convallis morbi odio odio elementum eu interdum eu tincidunt in');
insert into status_disp (status_id, clave, descripcion) values (180, 'OBS', 'cubilia curae mauris viverra diam vitae quam suspendisse potenti nullam porttitor');
insert into status_disp (status_id, clave, descripcion) values (181, 'REP', 'faucibus orci luctus et ultrices posuere cubilia curae mauris viverra diam vitae');
insert into status_disp (status_id, clave, descripcion) values (182, 'VIG', 'etiam faucibus cursus urna ut tellus nulla ut erat id mauris vulputate elementum nullam varius nulla facilisi cras non velit');
insert into status_disp (status_id, clave, descripcion) values (183, 'OBS', 'vitae quam suspendisse potenti nullam porttitor lacus at turpis donec posuere metus vitae ipsum aliquam non mauris morbi non');
insert into status_disp (status_id, clave, descripcion) values (184, 'AV', 'aliquet massa id lobortis convallis tortor risus dapibus augue vel accumsan tellus nisi eu');
insert into status_disp (status_id, clave, descripcion) values (185, 'VIG', 'a feugiat et eros vestibulum ac est lacinia nisi venenatis tristique fusce congue diam id');
insert into status_disp (status_id, clave, descripcion) values (186, 'FU', 'vehicula consequat morbi a ipsum integer a nibh in quis');
insert into status_disp (status_id, clave, descripcion) values (187, 'OBS', 'tristique fusce congue diam id ornare imperdiet sapien urna pretium nisl ut volutpat sapien arcu');
insert into status_disp (status_id, clave, descripcion) values (188, 'VIG', 'vestibulum quam sapien varius ut blandit non interdum in ante vestibulum ante ipsum primis in faucibus orci luctus et');
insert into status_disp (status_id, clave, descripcion) values (189, 'OBS', 'enim sit amet nunc viverra dapibus nulla suscipit ligula in lacus curabitur at ipsum ac tellus semper interdum mauris ullamcorper');
insert into status_disp (status_id, clave, descripcion) values (190, 'FU', 'est donec odio justo sollicitudin ut suscipit a feugiat et eros vestibulum ac est lacinia nisi venenatis tristique fusce congue');
insert into status_disp (status_id, clave, descripcion) values (191, 'FU', 'habitasse platea dictumst morbi vestibulum velit id pretium iaculis diam erat fermentum justo nec condimentum neque sapien placerat');
insert into status_disp (status_id, clave, descripcion) values (192, 'AV', 'nisi volutpat eleifend donec ut dolor morbi vel lectus in quam fringilla rhoncus');
insert into status_disp (status_id, clave, descripcion) values (193, 'FU', 'nunc nisl duis bibendum felis sed interdum venenatis turpis enim blandit mi in porttitor pede justo eu massa donec dapibus');
insert into status_disp (status_id, clave, descripcion) values (194, 'AV', 'aliquam erat volutpat in congue etiam justo etiam pretium iaculis justo in hac habitasse platea dictumst etiam faucibus cursus urna');
insert into status_disp (status_id, clave, descripcion) values (195, 'FU', 'in congue etiam justo etiam pretium iaculis justo in hac habitasse platea');
insert into status_disp (status_id, clave, descripcion) values (196, 'VIG', 'lobortis est phasellus sit amet erat nulla tempus vivamus in felis eu sapien cursus vestibulum proin eu');
insert into status_disp (status_id, clave, descripcion) values (197, 'FU', 'pretium nisl ut volutpat sapien arcu sed augue aliquam erat');
insert into status_disp (status_id, clave, descripcion) values (198, 'VIG', 'sapien cum sociis natoque penatibus et magnis dis parturient montes nascetur');
insert into status_disp (status_id, clave, descripcion) values (199, 'VIG', 'tempus vel pede morbi porttitor lorem id ligula suspendisse ornare consequat lectus in');
insert into status_disp (status_id, clave, descripcion) values (200, 'AV', 'nonummy maecenas tincidunt lacus at velit vivamus vel nulla eget eros elementum pellentesque');
insert into status_disp (status_id, clave, descripcion) values (201, 'VIG', 'in tempus sit amet sem fusce consequat nulla nisl nunc nisl duis bibendum felis sed interdum venenatis');
insert into status_disp (status_id, clave, descripcion) values (202, 'FU', 'erat fermentum justo nec condimentum neque sapien placerat ante nulla justo aliquam quis turpis eget elit sodales scelerisque mauris sit');
insert into status_disp (status_id, clave, descripcion) values (203, 'FU', 'nullam sit amet turpis elementum ligula vehicula consequat morbi a ipsum');
insert into status_disp (status_id, clave, descripcion) values (204, 'REP', 'hac habitasse platea dictumst aliquam augue quam sollicitudin vitae consectetuer eget rutrum at lorem integer');
insert into status_disp (status_id, clave, descripcion) values (205, 'REP', 'vitae quam suspendisse potenti nullam porttitor lacus at turpis donec posuere');
insert into status_disp (status_id, clave, descripcion) values (206, 'REP', 'vel nulla eget eros elementum pellentesque quisque porta volutpat erat quisque erat eros viverra eget congue');
insert into status_disp (status_id, clave, descripcion) values (207, 'REP', 'in libero ut massa volutpat convallis morbi odio odio elementum eu interdum eu tincidunt in');
insert into status_disp (status_id, clave, descripcion) values (208, 'OBS', 'elementum in hac habitasse platea dictumst morbi vestibulum velit id');
insert into status_disp (status_id, clave, descripcion) values (209, 'OBS', 'pellentesque viverra pede ac diam cras pellentesque volutpat dui maecenas tristique');
insert into status_disp (status_id, clave, descripcion) values (210, 'AV', 'cursus id turpis integer aliquet massa id lobortis convallis tortor risus dapibus augue vel');
insert into status_disp (status_id, clave, descripcion) values (211, 'AV', 'morbi a ipsum integer a nibh in quis justo maecenas rhoncus aliquam');
insert into status_disp (status_id, clave, descripcion) values (212, 'OBS', 'eu est congue elementum in hac habitasse platea dictumst morbi');
insert into status_disp (status_id, clave, descripcion) values (213, 'REP', 'ultrices enim lorem ipsum dolor sit amet consectetuer adipiscing elit proin interdum');
insert into status_disp (status_id, clave, descripcion) values (214, 'AV', 'suspendisse potenti cras in purus eu magna vulputate luctus cum sociis');
insert into status_disp (status_id, clave, descripcion) values (215, 'VIG', 'integer ac neque duis bibendum morbi non quam nec dui luctus rutrum nulla tellus');
insert into status_disp (status_id, clave, descripcion) values (216, 'FU', 'turpis a pede posuere nonummy integer non velit donec diam neque');
insert into status_disp (status_id, clave, descripcion) values (217, 'VIG', 'vehicula consequat morbi a ipsum integer a nibh in quis justo maecenas rhoncus aliquam lacus morbi quis');
insert into status_disp (status_id, clave, descripcion) values (218, 'VIG', 'ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae nulla dapibus');
insert into status_disp (status_id, clave, descripcion) values (219, 'AV', 'in quis justo maecenas rhoncus aliquam lacus morbi quis tortor id nulla ultrices aliquet maecenas');
insert into status_disp (status_id, clave, descripcion) values (220, 'OBS', 'cubilia curae nulla dapibus dolor vel est donec odio justo');
insert into status_disp (status_id, clave, descripcion) values (221, 'FU', 'pellentesque volutpat dui maecenas tristique est et tempus semper est quam pharetra magna ac');
insert into status_disp (status_id, clave, descripcion) values (222, 'VIG', 'primis in faucibus orci luctus et ultrices posuere cubilia curae nulla dapibus dolor vel est');
insert into status_disp (status_id, clave, descripcion) values (223, 'VIG', 'suspendisse potenti nullam porttitor lacus at turpis donec posuere metus vitae ipsum aliquam non');
insert into status_disp (status_id, clave, descripcion) values (224, 'REP', 'faucibus orci luctus et ultrices posuere cubilia curae donec pharetra magna');
insert into status_disp (status_id, clave, descripcion) values (225, 'AV', 'nunc purus phasellus in felis donec semper sapien a libero nam dui');
insert into status_disp (status_id, clave, descripcion) values (226, 'AV', 'eu est congue elementum in hac habitasse platea dictumst morbi vestibulum velit id pretium');
insert into status_disp (status_id, clave, descripcion) values (227, 'AV', 'libero convallis eget eleifend luctus ultricies eu nibh quisque id justo sit amet sapien dignissim');
insert into status_disp (status_id, clave, descripcion) values (228, 'OBS', 'ligula suspendisse ornare consequat lectus in est risus auctor sed tristique in tempus');
insert into status_disp (status_id, clave, descripcion) values (229, 'FU', 'quis justo maecenas rhoncus aliquam lacus morbi quis tortor id nulla ultrices aliquet maecenas leo odio condimentum');
insert into status_disp (status_id, clave, descripcion) values (230, 'FU', 'mi nulla ac enim in tempor turpis nec euismod scelerisque');
insert into status_disp (status_id, clave, descripcion) values (231, 'AV', 'nulla suspendisse potenti cras in purus eu magna vulputate luctus cum sociis natoque penatibus et magnis dis');
insert into status_disp (status_id, clave, descripcion) values (232, 'VIG', 'sed vestibulum sit amet cursus id turpis integer aliquet massa');
insert into status_disp (status_id, clave, descripcion) values (233, 'REP', 'tristique fusce congue diam id ornare imperdiet sapien urna pretium nisl ut volutpat sapien arcu sed augue');
insert into status_disp (status_id, clave, descripcion) values (234, 'OBS', 'eget congue eget semper rutrum nulla nunc purus phasellus in felis donec semper sapien a libero nam dui proin');
insert into status_disp (status_id, clave, descripcion) values (235, 'VIG', 'etiam vel augue vestibulum rutrum rutrum neque aenean auctor gravida sem praesent id massa id nisl');
insert into status_disp (status_id, clave, descripcion) values (236, 'REP', 'ipsum aliquam non mauris morbi non lectus aliquam sit amet diam in magna bibendum imperdiet nullam');
insert into status_disp (status_id, clave, descripcion) values (237, 'AV', 'cubilia curae donec pharetra magna vestibulum aliquet ultrices erat tortor sollicitudin mi sit amet lobortis sapien sapien non mi');
insert into status_disp (status_id, clave, descripcion) values (238, 'AV', 'a pede posuere nonummy integer non velit donec diam neque vestibulum eget vulputate ut ultrices vel augue vestibulum ante');
insert into status_disp (status_id, clave, descripcion) values (239, 'AV', 'quam pharetra magna ac consequat metus sapien ut nunc vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere');
insert into status_disp (status_id, clave, descripcion) values (240, 'VIG', 'id turpis integer aliquet massa id lobortis convallis tortor risus dapibus augue vel accumsan tellus nisi eu');
insert into status_disp (status_id, clave, descripcion) values (241, 'OBS', 'habitasse platea dictumst etiam faucibus cursus urna ut tellus nulla ut erat id mauris vulputate');
insert into status_disp (status_id, clave, descripcion) values (242, 'FU', 'faucibus orci luctus et ultrices posuere cubilia curae mauris viverra');
insert into status_disp (status_id, clave, descripcion) values (243, 'OBS', 'urna pretium nisl ut volutpat sapien arcu sed augue aliquam erat volutpat in congue etiam justo etiam');
insert into status_disp (status_id, clave, descripcion) values (244, 'VIG', 'turpis enim blandit mi in porttitor pede justo eu massa donec dapibus duis at velit eu est congue elementum in');
insert into status_disp (status_id, clave, descripcion) values (245, 'FU', 'interdum mauris ullamcorper purus sit amet nulla quisque arcu libero rutrum ac lobortis vel dapibus at diam nam tristique tortor');
insert into status_disp (status_id, clave, descripcion) values (246, 'OBS', 'elementum nullam varius nulla facilisi cras non velit nec nisi vulputate nonummy maecenas tincidunt lacus at velit vivamus');
insert into status_disp (status_id, clave, descripcion) values (247, 'AV', 'vivamus vel nulla eget eros elementum pellentesque quisque porta volutpat erat quisque');
insert into status_disp (status_id, clave, descripcion) values (248, 'AV', 'volutpat sapien arcu sed augue aliquam erat volutpat in congue etiam');
insert into status_disp (status_id, clave, descripcion) values (249, 'OBS', 'justo in blandit ultrices enim lorem ipsum dolor sit amet');
insert into status_disp (status_id, clave, descripcion) values (250, 'OBS', 'risus praesent lectus vestibulum quam sapien varius ut blandit non interdum in ante vestibulum');
insert into status_disp (status_id, clave, descripcion) values (251, 'VIG', 'vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae donec pharetra magna vestibulum aliquet ultrices erat');
insert into status_disp (status_id, clave, descripcion) values (252, 'VIG', 'commodo vulputate justo in blandit ultrices enim lorem ipsum dolor sit amet consectetuer adipiscing elit proin interdum mauris non ligula');
insert into status_disp (status_id, clave, descripcion) values (253, 'VIG', 'ante nulla justo aliquam quis turpis eget elit sodales scelerisque mauris');
insert into status_disp (status_id, clave, descripcion) values (254, 'VIG', 'nibh in quis justo maecenas rhoncus aliquam lacus morbi quis');
insert into status_disp (status_id, clave, descripcion) values (255, 'FU', 'sodales scelerisque mauris sit amet eros suspendisse accumsan tortor quis turpis sed ante vivamus tortor');
insert into status_disp (status_id, clave, descripcion) values (256, 'VIG', 'purus phasellus in felis donec semper sapien a libero nam dui proin leo');
insert into status_disp (status_id, clave, descripcion) values (257, 'VIG', 'sit amet consectetuer adipiscing elit proin risus praesent lectus vestibulum quam sapien varius ut blandit');
insert into status_disp (status_id, clave, descripcion) values (258, 'AV', 'consectetuer eget rutrum at lorem integer tincidunt ante vel ipsum praesent blandit lacinia');
insert into status_disp (status_id, clave, descripcion) values (259, 'REP', 'orci luctus et ultrices posuere cubilia curae duis faucibus accumsan odio');
insert into status_disp (status_id, clave, descripcion) values (260, 'FU', 'lacus curabitur at ipsum ac tellus semper interdum mauris ullamcorper purus sit amet nulla quisque');
insert into status_disp (status_id, clave, descripcion) values (261, 'REP', 'curae duis faucibus accumsan odio curabitur convallis duis consequat dui nec nisi volutpat eleifend donec ut dolor morbi vel lectus');
insert into status_disp (status_id, clave, descripcion) values (262, 'REP', 'ipsum praesent blandit lacinia erat vestibulum sed magna at nunc commodo');
insert into status_disp (status_id, clave, descripcion) values (263, 'FU', 'nam congue risus semper porta volutpat quam pede lobortis ligula sit amet eleifend pede libero');
insert into status_disp (status_id, clave, descripcion) values (264, 'VIG', 'dis parturient montes nascetur ridiculus mus vivamus vestibulum sagittis sapien cum sociis natoque');
insert into status_disp (status_id, clave, descripcion) values (265, 'VIG', 'eget elit sodales scelerisque mauris sit amet eros suspendisse accumsan tortor quis turpis sed ante vivamus tortor duis');
insert into status_disp (status_id, clave, descripcion) values (266, 'FU', 'lacus morbi quis tortor id nulla ultrices aliquet maecenas leo odio condimentum id');
insert into status_disp (status_id, clave, descripcion) values (267, 'AV', 'quam nec dui luctus rutrum nulla tellus in sagittis dui vel nisl duis ac');
insert into status_disp (status_id, clave, descripcion) values (268, 'AV', 'tempus semper est quam pharetra magna ac consequat metus sapien ut nunc vestibulum ante');
insert into status_disp (status_id, clave, descripcion) values (269, 'OBS', 'volutpat in congue etiam justo etiam pretium iaculis justo in hac');
insert into status_disp (status_id, clave, descripcion) values (270, 'FU', 'justo pellentesque viverra pede ac diam cras pellentesque volutpat dui maecenas tristique');
insert into status_disp (status_id, clave, descripcion) values (271, 'VIG', 'convallis duis consequat dui nec nisi volutpat eleifend donec ut dolor morbi vel');
insert into status_disp (status_id, clave, descripcion) values (272, 'AV', 'ac consequat metus sapien ut nunc vestibulum ante ipsum primis in faucibus orci luctus et ultrices');
insert into status_disp (status_id, clave, descripcion) values (273, 'REP', 'eu massa donec dapibus duis at velit eu est congue elementum in hac habitasse platea dictumst morbi vestibulum velit id');
insert into status_disp (status_id, clave, descripcion) values (274, 'VIG', 'tempus vel pede morbi porttitor lorem id ligula suspendisse ornare consequat lectus in est risus auctor sed');
insert into status_disp (status_id, clave, descripcion) values (275, 'AV', 'nulla integer pede justo lacinia eget tincidunt eget tempus vel pede morbi porttitor lorem');
insert into status_disp (status_id, clave, descripcion) values (276, 'AV', 'justo sit amet sapien dignissim vestibulum vestibulum ante ipsum primis in faucibus');
insert into status_disp (status_id, clave, descripcion) values (277, 'REP', 'rhoncus aliquam lacus morbi quis tortor id nulla ultrices aliquet maecenas leo odio condimentum id luctus nec molestie');
insert into status_disp (status_id, clave, descripcion) values (278, 'VIG', 'primis in faucibus orci luctus et ultrices posuere cubilia curae donec pharetra magna vestibulum aliquet ultrices erat tortor sollicitudin mi');
insert into status_disp (status_id, clave, descripcion) values (279, 'AV', 'dui vel sem sed sagittis nam congue risus semper porta volutpat quam pede lobortis ligula');
insert into status_disp (status_id, clave, descripcion) values (280, 'AV', 'vestibulum velit id pretium iaculis diam erat fermentum justo nec condimentum neque sapien placerat');
insert into status_disp (status_id, clave, descripcion) values (281, 'VIG', 'maecenas ut massa quis augue luctus tincidunt nulla mollis molestie lorem quisque ut erat curabitur gravida nisi at nibh');
insert into status_disp (status_id, clave, descripcion) values (282, 'OBS', 'aliquet pulvinar sed nisl nunc rhoncus dui vel sem sed sagittis nam congue');
insert into status_disp (status_id, clave, descripcion) values (283, 'REP', 'ante vestibulum ante ipsum primis in faucibus orci luctus et ultrices');
insert into status_disp (status_id, clave, descripcion) values (284, 'VIG', 'amet cursus id turpis integer aliquet massa id lobortis convallis tortor risus dapibus augue');
insert into status_disp (status_id, clave, descripcion) values (285, 'OBS', 'lacinia erat vestibulum sed magna at nunc commodo placerat praesent blandit nam nulla integer pede justo lacinia eget tincidunt');
insert into status_disp (status_id, clave, descripcion) values (286, 'REP', 'tempus vel pede morbi porttitor lorem id ligula suspendisse ornare consequat lectus');
insert into status_disp (status_id, clave, descripcion) values (287, 'OBS', 'tempus vivamus in felis eu sapien cursus vestibulum proin eu mi nulla ac enim in tempor turpis');
insert into status_disp (status_id, clave, descripcion) values (288, 'VIG', 'sem mauris laoreet ut rhoncus aliquet pulvinar sed nisl nunc rhoncus dui vel sem sed sagittis');
insert into status_disp (status_id, clave, descripcion) values (289, 'VIG', 'maecenas pulvinar lobortis est phasellus sit amet erat nulla tempus vivamus in felis eu sapien');
insert into status_disp (status_id, clave, descripcion) values (290, 'VIG', 'sapien cum sociis natoque penatibus et magnis dis parturient montes nascetur');
insert into status_disp (status_id, clave, descripcion) values (291, 'OBS', 'iaculis congue vivamus metus arcu adipiscing molestie hendrerit at vulputate vitae');
insert into status_disp (status_id, clave, descripcion) values (292, 'VIG', 'in hac habitasse platea dictumst morbi vestibulum velit id pretium iaculis diam erat fermentum justo nec condimentum neque sapien');
insert into status_disp (status_id, clave, descripcion) values (293, 'OBS', 'massa id nisl venenatis lacinia aenean sit amet justo morbi ut');
insert into status_disp (status_id, clave, descripcion) values (294, 'FU', 'pede justo lacinia eget tincidunt eget tempus vel pede morbi porttitor lorem id ligula');
insert into status_disp (status_id, clave, descripcion) values (295, 'OBS', 'sit amet sem fusce consequat nulla nisl nunc nisl duis bibendum felis sed interdum venenatis turpis enim blandit mi');
insert into status_disp (status_id, clave, descripcion) values (296, 'REP', 'turpis donec posuere metus vitae ipsum aliquam non mauris morbi');
insert into status_disp (status_id, clave, descripcion) values (297, 'VIG', 'elit proin risus praesent lectus vestibulum quam sapien varius ut blandit non interdum');
insert into status_disp (status_id, clave, descripcion) values (298, 'FU', 'vitae quam suspendisse potenti nullam porttitor lacus at turpis donec');
insert into status_disp (status_id, clave, descripcion) values (299, 'OBS', 'aliquam augue quam sollicitudin vitae consectetuer eget rutrum at lorem integer tincidunt ante vel ipsum praesent blandit');
insert into status_disp (status_id, clave, descripcion) values (300, 'OBS', 'sapien ut nunc vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae mauris');
