--
-- ER/Studio 8.0 SQL Code Generation
-- Company :      Hewlett-Packard
-- Project :      modelo_relacional.DM1
-- Author :       Mauricio Ramos
--
-- Date Created : Tuesday, February 02, 2021 13:38:56
-- Target DBMS : Oracle 11g
--

-- 
-- TABLE: CLIENTE 
--

CREATE TABLE CLIENTE(
    CLIENTE_ID          NUMBER(10, 0)    NOT NULL,
    NOMBRE              VARCHAR2(50)     NOT NULL,
    AP_PATERNO          VARCHAR2(40)     NOT NULL,
    AP_MATERNO          VARCHAR2(40),
    EMAIL               VARCHAR2(30)     NOT NULL,
    USERNAME            VARCHAR2(30)     NOT NULL,
    PASSWORD            VARCHAR2(40)     NOT NULL,
    DIRECCION           VARCHAR2(200)    NOT NULL,
    FECHA_NACIMIENTO    DATE             NOT NULL,
    CURP                VARCHAR2(20)     NOT NULL,
    FOTO                BLOB             NOT NULL,
    CONSTRAINT PK13 PRIMARY KEY (CLIENTE_ID)
)
;



-- 
-- TABLE: SESION 
--

CREATE TABLE SESION(
    SESION_ID         NUMBER(10, 0)    NOT NULL,
    TIPO              VARCHAR2(15)     NOT NULL,
    NUMERO            NUMBER(10, 0)    NOT NULL,
    FECHA_INICIO      DATE             NOT NULL,
    DURACION          VARCHAR2(40)     NOT NULL,
    TOTAL_CALORIAS    NUMBER(14, 4)    NOT NULL,
    CLIENTE_ID        NUMBER(10, 0)    NOT NULL,
    CONSTRAINT PK15 PRIMARY KEY (SESION_ID), 
    CONSTRAINT RefCLIENTE28 FOREIGN KEY (CLIENTE_ID)
    REFERENCES CLIENTE(CLIENTE_ID)
)
;



-- 
-- TABLE: CALORIAS 
--

CREATE TABLE CALORIAS(
    CALORIA_ID    NUMBER(10, 0)    NOT NULL,
    VALOR         NUMBER(13, 3)    NOT NULL,
    TIEMPO        DATE             NOT NULL,
    SESION_ID     NUMBER(10, 0)    NOT NULL,
    CONSTRAINT PK20 PRIMARY KEY (CALORIA_ID), 
    CONSTRAINT RefSESION21 FOREIGN KEY (SESION_ID)
    REFERENCES SESION(SESION_ID)
)
;



-- 
-- TABLE: CREDENCIAL 
--

CREATE TABLE CREDENCIAL(
    CREDENCIAL_ID    VARCHAR2(40)     NOT NULL,
    FOLIO            VARCHAR2(8)      NOT NULL,
    FECHA_INICIO     DATE             NOT NULL,
    FECHA_FIN        DATE             NOT NULL,
    CODIGO_BARRAS    VARCHAR2(13)     NOT NULL,
    CLIENTE_ID       NUMBER(10, 0)    NOT NULL,
    CONSTRAINT PK14 PRIMARY KEY (CREDENCIAL_ID), 
    CONSTRAINT RefCLIENTE15 FOREIGN KEY (CLIENTE_ID)
    REFERENCES CLIENTE(CLIENTE_ID)
)
;



-- 
-- TABLE: EXPEDIENTE_CLIENTE 
--

CREATE TABLE EXPEDIENTE_CLIENTE(
    EXPEDIENTE_CLIENTE_ID    NUMBER(10, 0)    NOT NULL,
    FECHA_REGISTRO           DATE             NOT NULL,
    PESO                     NUMBER(14, 4),
    MASA_CORPORAL            NUMBER(14, 4),
    ESTATURA                 NUMBER(14, 4),
    CLIENTE_ID               NUMBER(10, 0)    NOT NULL,
    CONSTRAINT PK21 PRIMARY KEY (EXPEDIENTE_CLIENTE_ID), 
    CONSTRAINT RefCLIENTE29 FOREIGN KEY (CLIENTE_ID)
    REFERENCES CLIENTE(CLIENTE_ID)
)
;



-- 
-- TABLE: SENSOR 
--

CREATE TABLE SENSOR(
    SENSOR_ID       NUMBER(10, 0)    NOT NULL,
    NUM_SERIE       VARCHAR2(20)     NOT NULL,
    FECHA_COMPRA    DATE             NOT NULL,
    MARCA           VARCHAR2(30)     NOT NULL,
    CLIENTE_ID      NUMBER(10, 0)    NOT NULL,
    CONSTRAINT PK16 PRIMARY KEY (SENSOR_ID), 
    CONSTRAINT RefCLIENTE16 FOREIGN KEY (CLIENTE_ID)
    REFERENCES CLIENTE(CLIENTE_ID)
)
;

--
-- ER/Studio 8.0 SQL Code Generation
-- Company :      Hewlett-Packard
-- Project :      modelo_relacional.DM1
-- Author :       Mauricio Ramos
--
-- Date Created : Tuesday, February 02, 2021 13:40:55
-- Target DBMS : Oracle 11g
--

-- 
-- TABLE: EMPLEADO 
--

CREATE TABLE EMPLEADO(
    EMPLEADO_ID           NUMBER(10, 0)    NOT NULL,
    NOMBRE                VARCHAR2(80)     NOT NULL,
    AP_PAT                VARCHAR2(40)     NOT NULL,
    AP_MAT                VARCHAR2(40),
    CURP                  VARCHAR2(20)     NOT NULL,
    NUM_TRABAJADOR        NUMBER(40, 0)    NOT NULL,
    RFC                   VARCHAR2(20)     NOT NULL,
    FECHA_NACIMIENTO      DATE             NOT NULL,
    EMAIL                 VARCHAR2(30)     NOT NULL,
    FOTO                  BLOB             NOT NULL,
    HUELLAS               BLOB,
    HUELLA_IZQ_INDICE     BLOB,
    HUELLA_IZQ_MENIQUE    BLOB,
    HUELLA_IZQ_ANULAR     BLOB,
    HUELLA_IZQ_MEDIO      BLOB,
    HUELLA_DER_PULGAR     BLOB,
    HUELLA_DER_INDICE     BLOB,
    HUELLA_DER_MENIQUE    BLOB,
    HUELLA_DER_ANULAR     BLOB,
    HUELLA_DER_MEDIO      BLOB,
    TIPO                  VARCHAR2(1)      NOT NULL,
    CONSTRAINT PK3 PRIMARY KEY (EMPLEADO_ID)
)
;



-- 
-- TABLE: ADMINISTRATIVO 
--

CREATE TABLE ADMINISTRATIVO(
    EMPLEADO_ID    NUMBER(10, 0)    NOT NULL,
    USER           VARCHAR2(30)     NOT NULL,
    PASSWORD       VARCHAR2(30)     NOT NULL,
    ROL            VARCHAR2(40)     NOT NULL,
    CERTIFICADO    BLOB             NOT NULL,
    CONSTRAINT PK4 PRIMARY KEY (EMPLEADO_ID), 
    CONSTRAINT RefEMPLEADO131 FOREIGN KEY (EMPLEADO_ID)
    REFERENCES EMPLEADO(EMPLEADO_ID)
)
;



-- 
-- TABLE: DISCIPLINA 
--

CREATE TABLE DISCIPLINA(
    DISCIPLINA_ID    NUMBER(10, 0)    NOT NULL,
    CLAVE            VARCHAR2(20)     NOT NULL,
    NOMBRE           VARCHAR2(40)     NOT NULL,
    DESCRIPCION      VARCHAR2(200)    NOT NULL,
    ICONO            BLOB             NOT NULL,
    CONSTRAINT PK8 PRIMARY KEY (DISCIPLINA_ID)
)
;



-- 
-- TABLE: GIMNASIO 
--

CREATE TABLE GIMNASIO(
    GIMNASIO_ID    NUMBER(10, 0)     NOT NULL,
    FOLIO          VARCHAR2(5)       NOT NULL,
    NOMBRE         VARCHAR2(50)      NOT NULL,
    DIRECCION      VARCHAR2(200)     NOT NULL,
    LATITUD        NUMBER(40, 20)    NOT NULL,
    LONGITUD       NUMBER(40, 20)    NOT NULL,
    TELEFONO       VARCHAR2(15)      NOT NULL,
    PAG_WEB        VARCHAR2(50)      NOT NULL,
    GERENTE_ID     NUMBER(10, 0)     NOT NULL,
    CONSTRAINT PK1 PRIMARY KEY (GIMNASIO_ID), 
    CONSTRAINT RefEMPLEADO301 FOREIGN KEY (GERENTE_ID)
    REFERENCES EMPLEADO(EMPLEADO_ID)
)
;



-- 
-- TABLE: STATUS_DISP 
--

CREATE TABLE STATUS_DISP(
    STATUS_ID      NUMBER(10, 0)    NOT NULL,
    CLAVE          VARCHAR2(5)      NOT NULL,
    DESCRIPCION    VARCHAR2(100)    NOT NULL,
    CONSTRAINT PK11 PRIMARY KEY (STATUS_ID)
)
;



-- 
-- TABLE: DISPOSITIVO 
--

CREATE TABLE DISPOSITIVO(
    INVENTARIO_ID       NUMBER(10, 0)    NOT NULL,
    NUM_INVENTARIO      VARCHAR2(18)     NOT NULL,
    NOMBRE              VARCHAR2(40)     NOT NULL,
    DESCRIPCION         VARCHAR2(200)    NOT NULL,
    FECHA_ADQ           DATE             NOT NULL,
    FECHA_STATUS        DATE             NOT NULL,
    STATUS_ACTUAL_ID    NUMBER(10, 0)    NOT NULL,
    GIMNASIO_ID         NUMBER(10, 0)    NOT NULL,
    CONSTRAINT PK9 PRIMARY KEY (INVENTARIO_ID), 
    CONSTRAINT RefGIMNASIO241 FOREIGN KEY (GIMNASIO_ID)
    REFERENCES GIMNASIO(GIMNASIO_ID),
    CONSTRAINT RefSTATUS_DISP71 FOREIGN KEY (STATUS_ACTUAL_ID)
    REFERENCES STATUS_DISP(STATUS_ID)
)
;



-- 
-- TABLE: GIMNASIO_EMPLEADO 
--

CREATE TABLE GIMNASIO_EMPLEADO(
    GIMANSIO_EMPLEADO_ID    NUMBER(10, 0)    NOT NULL,
    EMPLEADO_ID             NUMBER(10, 0)    NOT NULL,
    GIMNASIO_ID             NUMBER(10, 0)    NOT NULL,
    CONSTRAINT PK18 PRIMARY KEY (GIMANSIO_EMPLEADO_ID), 
    CONSTRAINT RefGIMNASIO191 FOREIGN KEY (GIMNASIO_ID)
    REFERENCES GIMNASIO(GIMNASIO_ID),
    CONSTRAINT RefEMPLEADO201 FOREIGN KEY (EMPLEADO_ID)
    REFERENCES EMPLEADO(EMPLEADO_ID)
)
;



-- 
-- TABLE: GYM_MATERIAL_MULTIMEDIA 
--

CREATE TABLE GYM_MATERIAL_MULTIMEDIA(
    MULTIMEDIA_ID    NUMBER(10, 0)    NOT NULL,
    TIPO             VARCHAR2(1)      NOT NULL,
    CONTENIDO        BLOB             NOT NULL,
    FECHA_INICIO     DATE             NOT NULL,
    FECHA_FIN        DATE             NOT NULL,
    GIMNASIO_ID      NUMBER(10, 0)    NOT NULL,
    CONSTRAINT PK2 PRIMARY KEY (MULTIMEDIA_ID), 
    CONSTRAINT RefGIMNASIO11 FOREIGN KEY (GIMNASIO_ID)
    REFERENCES GIMNASIO(GIMNASIO_ID)
)
;



-- 
-- TABLE: HISTORICO_STATUS_DISP 
--

CREATE TABLE HISTORICO_STATUS_DISP(
    HISTORICO_ID     NUMBER(10, 0)    NOT NULL,
    FECHA_STATUS     DATE             NOT NULL,
    STATUS_ID        NUMBER(10, 0)    NOT NULL,
    INVENTARIO_ID    NUMBER(10, 0)    NOT NULL,
    CONSTRAINT PK12 PRIMARY KEY (HISTORICO_ID), 
    CONSTRAINT RefDISPOSITIVO231 FOREIGN KEY (INVENTARIO_ID)
    REFERENCES DISPOSITIVO(INVENTARIO_ID),
    CONSTRAINT RefSTATUS_DISP41 FOREIGN KEY (STATUS_ID)
    REFERENCES STATUS_DISP(STATUS_ID)
)
;



-- 
-- TABLE: INSTRUCTOR 
--

CREATE TABLE INSTRUCTOR(
    EMPLEADO_ID    NUMBER(10, 0)    NOT NULL,
    CEDULA         VARCHAR2(40)     NOT NULL,
    AÑOS_EXP       NUMBER(10, 0)    NOT NULL,
    SUPLENTE_ID    VARCHAR2(40)     NOT NULL,
    CONSTRAINT PK5 PRIMARY KEY (EMPLEADO_ID), 
    CONSTRAINT RefEMPLEADO141 FOREIGN KEY (EMPLEADO_ID)
    REFERENCES EMPLEADO(EMPLEADO_ID)
)
;



-- 
-- TABLE: SALA 
--

CREATE TABLE SALA(
    SALA_ID             NUMBER(10, 0)    NOT NULL,
    CLAVE               VARCHAR2(3)      NOT NULL,
    NOMBRE              VARCHAR2(40)     NOT NULL,
    CAPACIDAD           NUMBER(10, 0)    NOT NULL,
    EMPLEADO_SALA_ID    NUMBER(10, 0)    NOT NULL,
    CONSTRAINT PK7 PRIMARY KEY (SALA_ID), 
    CONSTRAINT RefADMINISTRATIVO111 FOREIGN KEY (EMPLEADO_SALA_ID)
    REFERENCES ADMINISTRATIVO(EMPLEADO_ID)
)
;



-- 
-- TABLE: SALA_DISCIPLINA 
--

CREATE TABLE SALA_DISCIPLINA(
    SALA_DISCIPLINA_ID    NUMBER(10, 0)    NOT NULL,
    SALA_ID               NUMBER(10, 0)    NOT NULL,
    DISCIPLINA_ID         NUMBER(10, 0)    NOT NULL,
    CONSTRAINT PK17 PRIMARY KEY (SALA_DISCIPLINA_ID), 
    CONSTRAINT RefSALA91 FOREIGN KEY (SALA_ID)
    REFERENCES SALA(SALA_ID),
    CONSTRAINT RefDISCIPLINA101 FOREIGN KEY (DISCIPLINA_ID)
    REFERENCES DISCIPLINA(DISCIPLINA_ID)
)
;



-- 
-- TABLE: URL_INSTRUCTOR 
--

CREATE TABLE URL_INSTRUCTOR(
    URL_ID         NUMBER(10, 0)    NOT NULL,
    DIRECCION      VARCHAR2(50)     NOT NULL,
    EMPLEADO_ID    NUMBER(10, 0)    NOT NULL,
    CONSTRAINT PK6 PRIMARY KEY (URL_ID), 
    CONSTRAINT RefINSTRUCTOR121 FOREIGN KEY (EMPLEADO_ID)
    REFERENCES INSTRUCTOR(EMPLEADO_ID)
)
;


